"""Data models shared by every stage of the pipeline.

Design note: every stage (search -> extract -> summarize -> cluster -> write)
passes around the same small, explicit data structures instead of loose dicts.
That gives us one place that documents "what is a paper in this system", and it
makes typos (paper["tittle"]) fail loudly instead of silently returning None.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Paper:
    """Metadata for one arXiv paper, exactly as reported by the arXiv API.

    Everything here is *ground truth* from arXiv. Anything an LLM produces
    later (summaries, themes, ...) is stored in separate structures so we never
    mix trusted metadata with model-generated text.
    """

    arxiv_id: str  # e.g. "2401.00001v2" or old-style "hep-th/9901001v1"
    title: str
    authors: list[str]
    abstract: str
    year: int  # year of the FIRST version (arXiv's "published" date)
    abs_url: str  # landing page, e.g. https://arxiv.org/abs/2401.00001v2
    pdf_url: str  # direct PDF link (may still fail to download; see Step 2)
    categories: list[str] = field(default_factory=list)  # e.g. ["cs.CL", "cs.AI"]

    def citation(self) -> str:
        """Build the citation string used in the final review.

        Deliberately generated by plain Python from trusted metadata, never by
        the LLM. LLMs are known to invent plausible-looking citations, which
        would be a fatal flaw in a literature-review tool.
        """
        if not self.authors:
            author_str = "Unknown authors"
        elif len(self.authors) <= 3:
            author_str = ", ".join(self.authors)
        else:
            author_str = f"{self.authors[0]} et al."
        return (
            f"{author_str} ({self.year}). *{self.title}*. "
            f"arXiv:{self.arxiv_id}. {self.abs_url}"
        )


@dataclass
class PaperContent:
    """The text we hand to the LLM for one paper, plus where it came from."""

    paper: Paper
    text: str
    source: str  # "full_text" or "abstract_only"
    note: str = ""  # why we fell back to the abstract, if we did


@dataclass
class PaperNotes:
    """Structured notes the LLM extracted for one paper (LLM-written, unverified)."""

    paper: Paper
    source: str
    paper_type: str = "other"
    core_method: str = ""
    key_findings: list[str] = field(default_factory=list)
    datasets: list[str] = field(default_factory=list)
    relation_to_topic: str = ""
    open_problems: list[str] = field(default_factory=list)
    relevance: int = 0
    error: str = ""

    @property
    def ok(self) -> bool:
        return not self.error


@dataclass
class Theme:
    name: str
    description: str
    notes: list[PaperNotes]


@dataclass
class Gap:
    title: str
    description: str
    notes: list[PaperNotes]
